#%RAML 1.0 Library

types:
  getContactResponse: !include ../types/response/get-contacts-response.raml
  postContactRequest: !include ../types/request/post-contacts-request.raml
  postContactResponse: !include ../types/response/post-contacs-response.raml