#%RAML 1.0 DataType
description: post contact request data type

type: object
properties:
  firstname:
    type: string
  lastname:
    type: string
  emailaddress1:
    type: string
  emailpreferred:
    type: boolean
  donotemail:
    type: string
